### PR TITLE
Add Call-To-Action Entry for Resource Linking

### LINKED ISSUE #23: Support "call to action" entry in context pad
### What should we do?
Support a highlighted context pad entry (which will be used for resource linking in bpmn):

###  Why should we do it?
As part of the intuitive modeling initiative, see https://github.com/camunda/product-hub/issues/1917

### PR DESCRIPTION
**Pull request by smbea**
Adds a separate context pad provider that adds a call-to-action entry to link a resource (BPMN, DMN or Form). The entry indicates whether a resource is linked or not. Clicking the entry fires an event with the relevant context for handling the linking of the resource.

brave_a2r2PvADZi

---

Closes #23
Related to https://github.com/camunda/product-hub/issues/1917

### CODE REVIEW

**Comment by philippfromme** [comment]
@smbea Unfortunately, since you opened the pull request, I cannot request a review from you. 😞

**Comment by smbea** [comment]
@philippfromme will look at this today

**Comment by smbea** [comment]
It seems the hover state doesn't cover the full entry:

https://github.com/camunda/improved-canvas/assets/25825387/dd94d1ec-798f-4de9-a0ec-e785def48986

**Comment by smbea** [comment]
I think the rest looks good. I also can't give an official review since I opened the PR 😅

**Comment by philippfromme** [comment]
> It seems the hover state doesn't cover the full entry:

This is analogous to the non-call-to-action entries.

brave_VW4NYtZCXF

I also mentioned it here: https://github.com/camunda/product-hub/issues/1917#issuecomment-1908965052. 😇

**Comment by philippfromme** [comment]
I had a chat with @marcellobarile and it turns out we forgot about form linking for start events which is supported by the Web Modeler. I will add it. 👷🏻‍♂️

**Comment by philippfromme** [comment]
I've added support for none start events (enabled by default, can be disabled through configuration). Should be good to go now.

brave_UsqaQ8PHPL

**Review by marstamm — APPROVED** [review]
Discussed with @philippfromme , we will merge this now but want to transfer adding the link button to the webmodeler (or application that handles the event) in the long term

**Pull request merged**
