### PR TITLE
Boundary append/attach node

### PR DESCRIPTION
**Pull request by smbea**
I made it so we auto place if it's the first boundary event, but trigger create if not. I found this a good compromise between trying to properly place it and saving the user some clicks. Let me know what you think

https://github.com/camunda/improved-canvas/assets/25825387/1eac00d7-ce00-4e02-83f1-75f97323e33a

### CODE REVIEW

**Review by nikku — APPROVED** [review]
> I made it so we auto place if it's the first boundary event, but trigger create if not. I found this a good compromise between trying to properly place it and saving the user some clicks. Let me know what you think

Marvelous :star2:

**Comment by nikku** [comment]
What I found in the process of reviewing this is that the connect tool does not support "drag out to connect start", but only "click to connect start":

capture CW4Z23_optimized


As I can drag out a text annotation, I'd expect the same thing for the connect tool.

**Comment by smbea** [comment]
> What I found in the process of reviewing this is that the connect tool does not support "drag out to connect start", but only "click to connect start":

That is strange and unexpected. I will follow up on this

**Comment by philippfromme** [comment]
The icon doesn't seem to be 💯 centered:

brave_r83UK7ga8W

brave_jbid8iFTHf

**Comment by smbea** [comment]
> The icon doesn't seem to be 💯 centered:
> Is it only me?

It doesn't happen for me. But I can try to test in other screen sizes. Maybe that's the issue

**Comment by barmac** [comment]
> Is it only me?

I can see this too. This is sometimes caused by fractions in the position/size. Notice that we may not notice this on ultra-high resolution screens on Macs.

**Comment by philippfromme** [comment]
I have this problem even with scaling set to 100%. 🤔

**Comment by nikku** [comment]
@philippfromme Please create a follow-up issue so we can look into that in an orderly fashion. Looks disturbing, I agree :see_no_evil:

**Comment by philippfromme** [comment]
Forget about my problem. I accidentally had browser zoom enabled. Works for me now. 🙈

**Pull request merged**
