### PR TITLE
Support for dmn

### LINKED ISSUE #21: Implement context pad for DMN
### What should we do?
Implemented new and updated context pad + high contrast canvas for DMN: 

- Context pad for DMN

###  Why should we do it?
As part of the intuitive modeling initiative, see https://github.com/camunda/product-hub/issues/1948

### PR DESCRIPTION
**Pull request by smbea**
~~Best to wait for https://github.com/camunda/improved-canvas/pull/20 to be merged so big conflicts are avoided~~ ✅
Closes #21 

This pr:
* establishes common, bpmn and dmn modules - https://github.com/camunda/improved-canvas/pull/22/commits/95048f7f896734689e84b793e2419a6a2fd398a4
* implements support for dmn - https://github.com/camunda/improved-canvas/pull/22/commits/a43f094db26fb85822ca14528d13130ff2e57b31
* changes context pad to white background as discussed - https://github.com/camunda/improved-canvas/pull/22/commits/0f814c37bd406fe0a5c70075e7a7d0f972eed99a

### CODE REVIEW

**Comment by philippfromme** [comment]
I'm checking out the DMN support and I can't see a context pad for anything that's not a decision. 🤔 

brave_s5ikDCvT8A

**Comment by smbea** [comment]
@philippfromme my bad 🙈, I fixed it now

**Comment by barmac** [comment]
There is no popup for text annotation:

https://github.com/camunda/improved-canvas/assets/28307541/9df565b6-93af-4cb9-9260-3f67e5802588

**Comment by smbea** [comment]
@barmac turns out this is a problem [at the core](https://github.com/bpmn-io/dmn-js/blob/develop/packages/dmn-js-drd/src/features/context-pad/ContextPadProvider.js#L222). I will work on it in `dmn-js`.

**Review by barmac — APPROVED** [review]
We could also consider maintaining the order as in the palette:
image

If I were to define new order, I'd put knowledge source at the end as a less important element.

Other than that, it looks good.

**Comment by smbea** [comment]
> If I were to define new order, I'd put knowledge source at the end as a less important element.

I think this makes sense and follows the palette order. I updated.

**Pull request merged**
