### PR TITLE
Add Quick Append and Attach

### PR DESCRIPTION
**Pull request by philippfromme**
brave_5AxZaV3kpR

Can be tried out at https://camunda.github.io/improved-canvas/.

# Changes

* added quick append that uses append entries provided by context pad
* added quick attach that provides attach entries for most common bondary events (according to @NPDeehan)
* styled quick append and attach to match context pad
* moved context pad up a bit
* reduced the context pad padding to occupy less space
* removed plus icon from comments context pad entry
* removed text annotation entry from context pad

### CODE REVIEW

**Comment by lmbateman** [comment]
Looks great! My only outstanding concern, which is minor, is that when an element is in edit mode, the edit box overlaps the boundary event append button and append pad. I think the former is OK, but the latter is a bit odd -- if I've hovered over the boundary event append button to pull up the pad, then I would expect the pad to be on top. 

image

image

**Comment by philippfromme** [comment]
@lmbateman We are aware of the issue (cf. https://github.com/camunda/web-modeler/issues/8477) and are working on fixing it (cc @marstamm). It's not part of this PR, so you can ignore it for now.

**Comment by marstamm** [comment]
related to https://github.com/bpmn-io/diagram-js-direct-editing/issues/23

**Review by lmbateman — APPROVED** [review]

**Comment by nikku** [comment]
I gave it another round of tests and found it to work well :clap:

**Pull request merged**
